(defun quicksort (vec comp)
  (when (> (length vec) 1)
    (let ((pivot-i 0)
          (pivot (aref vec (1- (length vec)))))
      (dotimes (i (1- (length vec)))
        (when (funcall comp (aref vec i) pivot)
          (rotatef (aref vec i) (aref vec pivot-i))
          (incf pivot-i)))
      (rotatef (aref vec (1- (length vec))) (aref vec pivot-i))
      (quicksort (subseq vec 0 pivot-i) comp)
      (quicksort (subseq vec (1+ pivot-i)) comp)))
  vec)
